FROM python:3.12-slim

WORKDIR /app

COPY requirements.http.txt .

RUN pip install --no-cache-dir -r requirements.http.txt

COPY sources/http ./sources/http

EXPOSE 8000

CMD ["uvicorn", "sources.http.api:app", "--host", "0.0.0.0", "--port", "8000"]